### PR TITLE
Isomer removed scrolling bar

### PR DESCRIPTION
**Pull request by isomer04**
## Description

Remove the scroll bar on the app so that you don't need to scroll down the page to see the footer.

## Related Issue

-   [x] Is this related to a specific issue? Is so please specify:
#44 
## Type of Changes

Use a check for ✓ the following type of changes:

|     | Type                       |
| --- | -------------------------- |
|✓ | :bug: Bug fix              |
|  | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

[If applicable, include a picture of the behavior before the changes were made. I.e. a screenshot of the behavior before the changes were made.]

### After

[I.e. a screenshot of the behavior after the changes were made.]

## Testing Steps / QA Criteria

[Describe the steps taken to test upcoming changes. Describe any additional testing that needs to be done beyond the steps outlined above. This might include manual testing, exploratory testing, or other types of testing that can't be easily automated.]

## Checklist:

-   [ ] This PR is up to date with the development branch, and merge conflicts have been resolved
-   [ ] My code follows the style guidelines of this project
-   [ ] I have executed npm run lint and resolved any outstanding errors. 
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by IntelliJinceTech** [comment]
Per discord: 
image
Having issues when I have more boards than there is space. I propose having a scrollbar on the screen that shows all your available boards but no scroll while actually in the board? Thoughts?

**Review by IntelliJinceTech — CHANGES_REQUESTED** [review]
Need to make the board grid scrollable but not in the workspace

**Comment by IntelliJinceTech** [comment]
Dashboard looks better but still getting a scroll bar on workspace? Are you getting that too? 
image

**Comment by isomer04** [comment]
> Dashboard looks better but still getting a scroll bar on workspace? Are you getting that too? image

Not this PR. I think I worked on another PR. Let's remove this PR

**Pull request closed without merging**
